version: "2"
linters:
  default: none
  enable:
    - copyloopvar
    - dupl
    - durationcheck
    - errcheck
    - forcetypeassert
    - gocognit
    - gocyclo
    - godot
    - govet
    - ineffassign
    - makezero
    - misspell
    - nilerr
    - predeclared
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
  settings:
    dupl:
      threshold: 400
    gocyclo:
      min-complexity: 40
    gocognit:
      min-complexity: 70
    revive:
      rules:
        - name: package-comments
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
    rules:
      - linters:
          - dupl
          - gocognit
          - gocyclo
        path: _test\.go$
      - linters:
          - dupl
        path: _credential_resource\.go$
issues:
  max-same-issues: 0
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$

