version: 2

# Visit https://golangci-lint.run/ for usage documentation
# and information on other useful linters
issues:
  max-same-issues: 0

linters:
  disable:
    - errcheck
  enable:
    - durationcheck
    - copyloopvar
    - forcetypeassert
    - godot
    - ineffassign
    - makezero
    - misspell
    - nilerr
    - predeclared
    - staticcheck
    - unconvert
    - unparam
    - unused
    - govet
    